Add packages required for demo.ipynb
- Add `ipykernel` so the user can run the notebook
- Add `tomli` so the package version can be read from `pyproject.toml`
- Upgrade `datasets` to `>=4.0`. The current version 3.6 results in the
error

```python
❯ python -c "import datasets; print(datasets.__version__)"
3.6.0
❯ uv run python
Python 3.12.9 (main, Mar 17 2025, 21:36:21) [Clang 20.1.0 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from datasets import load_dataset
>>> load_dataset("autogluon/chronos_datasets", "monash_tourism_monthly")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/bwilliams/My Drive/tmp/datasets/datasets_venv/lib/python3.12/site-packages/datasets/load.py", line 2062, in load_dataset
    builder_instance = load_dataset_builder(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bwilliams/My Drive/tmp/datasets/datasets_venv/lib/python3.12/site-packages/datasets/load.py", line 1819, in load_dataset_builder
    builder_instance: DatasetBuilder = builder_cls(
                                       ^^^^^^^^^^^^
  File "/Users/bwilliams/My Drive/tmp/datasets/datasets_venv/lib/python3.12/site-packages/datasets/builder.py", line 395, in __init__
    self.info = DatasetInfo.from_directory(self._cache_dir)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bwilliams/My Drive/tmp/datasets/datasets_venv/lib/python3.12/site-packages/datasets/info.py", line 279, in from_directory
    return cls.from_dict(dataset_info_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bwilliams/My Drive/tmp/datasets/datasets_venv/lib/python3.12/site-packages/datasets/info.py", line 284, in from_dict
    return cls(**{k: v for k, v in dataset_info_dict.items() if k in field_names})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 20, in __init__
  File "/Users/bwilliams/My Drive/tmp/datasets/datasets_venv/lib/python3.12/site-packages/datasets/info.py", line 170, in __post_init__
    self.features = Features.from_dict(self.features)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bwilliams/My Drive/tmp/datasets/datasets_venv/lib/python3.12/site-packages/datasets/features/features.py", line 1888, in from_dict
    obj = generate_from_dict(dic)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bwilliams/My Drive/tmp/datasets/datasets_venv/lib/python3.12/site-packages/datasets/features/features.py", line 1468, in generate_from_dict
    return {key: generate_from_dict(value) for key, value in obj.items()}
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bwilliams/My Drive/tmp/datasets/datasets_venv/lib/python3.12/site-packages/datasets/features/features.py", line 1474, in generate_from_dict
    raise ValueError(f"Feature type '{_type}' not found. Available feature types: {list(_FEATURE_TYPES.keys())}")
ValueError: Feature type 'List' not found. Available feature types: ['Value', 'ClassLabel', 'Translation', 'TranslationVariableLanguages', 'LargeList', 'Sequence', 'Array2D', 'Array3D', 'Array4D', 'Array5D', 'Audio', 'Image', 'Video', 'Pdf']
>>>
```